---
title: "juvenile simulations"
author: "steph"
date: '2023-08-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_knit$set(root.dir="C:/Users/Steph/OneDrive - Texas A&M University/Thrushes/survival/data/")
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


```{r, include=FALSE}
#load packages
pkgs<-c("tidyverse","HIest","viridis","ggpubr","ggExtra")
sapply(pkgs,library,character.only=T); rm(pkgs)
theme_set(theme_classic())

#read in survival functions
source("../thrush_survival/00_functions_survival.R")

#read in file with HIest estimates, individual names, and survival data
HI_thrush<-read.csv("thrush_survival_230712.csv"); HI_thrush$X<-NULL

HI_sims<-read.csv("eggs.hiest.20230805.all.csv",header=F); HI_sims$V1<-NULL

poly.all<-data.frame(X.co=rep(c(0,0.5,1)), #make triangle polygon for plotting
                     Y.co=rep(c(0,1,0)))

```


```{r, include=F}

HI_juvie<-HI_thrush%>%filter(age_release=="HY"&release_site=="Pemberton")

HI_sims<-HI_sims%>%
  rename(ancestry=V2,heterozygosity=V3,runID=V4)%>%
  mutate(ancestry=(ancestry*(-1)+1))
```


```{r,fig.width=(18/2.54),fig.height=(7/2.54)}

p1<-ggplot(data=HI_juvie,
       aes(x=ancestry,y=heterozygosity))+
  geom_polygon(data=poly.all,aes(x=X.co,y=Y.co),fill=NA,colour="black")+
  geom_point(size=3,colour="coral3",shape=1)+
  coord_equal()+xlab("Ancestry")+ylab("Heterozygosity")
p1<-ggMarginal(p1,type="histogram",fill="coral3")
p1

p2<-ggplot(data=HI_sims,
           aes(x=ancestry,y=heterozygosity))+
  geom_polygon(data=poly.all,aes(x=X.co,y=Y.co),fill=NA,colour="black")+
  geom_point(size=3,colour="cadetblue",shape=1)+
  coord_equal()+xlab("Ancestry")+ylab("Heterozygosity")
p2<-ggMarginal(p2,type="histogram",fill="cadetblue")
p2


fig4<-ggarrange(p2,p1,labels=c("A","B"))
ggsave(filename="../figures/Fig4.pdf",device="pdf",plot=fig4,width=18,height=7,units="cm")


```




```{r}

ks.test(HI_sims$ancestry,HI_juvie$ancestry)
ks.test(HI_sims$heterozygosity,HI_juvie$heterozygosity)

```